package marker

import (
	"bytes"
	"testing"
)

func TestFillIsDeterministicAndNonTrivial(t *testing.T) {
	a := make([]byte, BufferSize)
	b := make([]byte, BufferSize)
	Fill(a)
	Fill(b)

	if !bytes.Equal(a, b) {
		t.Fatal("Fill returned different data for identical buffers")
	}
	if bytes.Equal(a, make([]byte, len(a))) {
		t.Fatal("Fill returned only zero bytes")
	}
	if !bytes.Equal(a[:SearchSize], SearchPattern()) {
		t.Fatal("SearchPattern does not match the prefix generated by Fill")
	}
}
